import {useEffect,useMemo,useState} from 'react';
import {createBrowserRouter,NavLink,Outlet,RouterProvider,Link} from 'react-router-dom';
import {supabase} from './lib/supabase';
import {track} from './lib/analytics';

type ModuleCard={to:string;icon:string;title:string;description:string};
type Term={term:string;definition:string;example?:string|null;librasStatus:string};
const icons:Record<string,string>={explorar:'🔍',detetive:'🕵️',laboratorio:'🧪',construtor:'⚛️',glossario:'🤟',missoes:'🌎'};
const fallbackModules:ModuleCard[]=[
 {to:'/explorar',icon:'🔍',title:'Explorar',description:'Descubra o que realmente é uma reação.'},
 {to:'/detetive',icon:'🕵️',title:'Detetive das Reações',description:'Encontre pistas e construa evidências.'},
 {to:'/laboratorio',icon:'🧪',title:'Laboratório Visual',description:'Preveja, experimente e compare.'},
 {to:'/construtor',icon:'⚛️',title:'Construtor de Reações',description:'Monte e equilibre os átomos.'},
 {to:'/glossario',icon:'🤟',title:'Glossário Bilíngue',description:'Português + Libras + representação visual.'},
 {to:'/missoes',icon:'🌎',title:'Missões do Cotidiano',description:'Veja a Química na vida real.'}
];
const fallbackTerms:Term[]=[
 {term:'Átomo',definition:'Unidade básica que compõe a matéria.',librasStatus:'pending'},
 {term:'Molécula',definition:'Conjunto de dois ou mais átomos ligados.',librasStatus:'pending'},
 {term:'Reação química',definition:'Transformação em que reagentes formam novas substâncias.',librasStatus:'pending'},
 {term:'Reagente',definition:'Substância presente no início de uma reação.',librasStatus:'pending'},
 {term:'Produto',definition:'Substância formada ao final de uma reação.',librasStatus:'pending'},
 {term:'Conservação da massa',definition:'Em sistema fechado, a massa total é conservada durante a reação.',librasStatus:'pending'}
];
function Libras({label='Vídeo em Libras validado será inserido aqui'}:{label?:string}){return <div className="libras"><span>🤟</span><div><strong>Libras</strong><p>{label}</p></div></div>}
function Shell(){return <div className="shell"><header><div><strong>ReAção Visual</strong><span>Veja. Sinalize. Experimente. Compreenda.</span></div></header><main><Outlet/></main><nav><NavLink to="/">Início</NavLink><NavLink to="/explorar">Explorar</NavLink><NavLink to="/laboratorio">Lab</NavLink><NavLink to="/glossario">Glossário</NavLink><NavLink to="/sobre">Sobre</NavLink></nav></div>}
function Home(){const [mods,setMods]=useState(fallbackModules);useEffect(()=>{if(!supabase)return;supabase.from('modules').select('slug,title,description,sort_order').eq('published',true).order('sort_order').then(({data})=>{if(data?.length)setMods(data.map(x=>({to:'/'+x.slug,icon:icons[x.slug]||'🧪',title:x.title,description:x.description||''})))})},[]);return <section className="page"><div className="hero"><p className="eyebrow">Laboratório bilíngue de reações químicas</p><h1>🧪 Você consegue descobrir quando uma transformação é uma reação química?</h1><p>Observe o fenômeno, formule uma hipótese e investigue.</p></div><div className="flow"><span>👀 Observe</span><span>💭 Preveja</span><span>🧪 Investigue</span><span>💬 Explique</span></div><h2>Escolha como começar</h2><div className="grid">{mods.map(m=><Link key={m.to} to={m.to} className="card" onClick={()=>track('module_started',{module_path:m.to,module_title:m.title})}><span className="icon">{m.icon}</span><div><h3>{m.title}</h3><p>{m.description}</p></div></Link>)}</div><div className="note"><strong>🤟 Libras faz parte de cada conceito</strong><p>Vídeos validados aparecem ao lado do conteúdo, não em uma área separada.</p></div></section>}
function Explore(){const cases=[['🧊','Gelo derretendo','mudança física'],['🔥','Madeira queimando','provável reação química'],['🍎','Maçã escurecendo','provável reação química'],['✂️','Papel cortado','mudança física'],['🥖','Pão crescendo','provável reação química'],['💊','Comprimido efervescente','provável reação química']];const [ans,setAns]=useState<Record<number,string>>({});return <section className="page"><h1>O que é uma reação?</h1><p>Classifique cada situação. O objetivo é investigar, não apenas acertar.</p><Libras/><div className="stack">{cases.map((c,i)=><article className="panel" key={c[1]}><h2>{c[0]} {c[1]}</h2><div className="choices">{['mudança física','provável reação química','quero investigar mais'].map(o=><button className={ans[i]===o?'choice active':'choice'} onClick={()=>setAns({...ans,[i]:o})} key={o}>{o}</button>)}</div>{ans[i]&&<p className="feedback">Sua hipótese: <strong>{ans[i]}</strong>. Referência científica: {c[2]}.</p>}</article>)}</div></section>}
function Detective(){const scenes=[['🫧','Formação de bolhas'],['🎨','Mudança de cor'],['⬇️','Formação de precipitado'],['🌡️','Alteração de energia']];return <section className="page"><h1>Detetive das Reações</h1><p>Esses sinais podem ser evidências, mas isoladamente não provam uma reação química.</p><div className="grid">{scenes.map(s=><article className="card static" key={s[1]}><span className="icon">{s[0]}</span><div><h3>{s[1]}</h3><p>Observe o contexto e procure outras evidências antes de concluir.</p></div></article>)}</div></section>}
function Lab(){const [a,setA]=useState(''),[b,setB]=useState('');const diff=a&&b?(Number(b)-Number(a)).toFixed(2):null;return <section className="page"><h1>Laboratório Visual</h1><div className="safety">🟢 Baixo risco — requer supervisão adequada e uso correto dos materiais. Não use recipiente rígido totalmente fechado.</div><Libras/><h2>O gás invisível</h2><p>Vinagre + bicarbonato de sódio, usando um balão para manter o gás no sistema.</p><div className="inputs"><label>Massa inicial (g)<input inputMode="decimal" value={a} onChange={e=>setA(e.target.value)}/></label><label>Massa final (g)<input inputMode="decimal" value={b} onChange={e=>setB(e.target.value)}/></label></div>{diff&&<div className="result">Diferença: <strong>{diff} g</strong></div>}<div className="equation">NaHCO₃ + CH₃COOH → CH₃COONa + H₂O + CO₂</div><div className="tabs"><article><strong>Macroscópico</strong><p>Bolhas aparecem e o balão infla.</p></article><article><strong>Microscópico</strong><p>As partículas se reorganizam, formando novas substâncias.</p></article><article><strong>Simbólico</strong><p>A equação representa reagentes e produtos.</p></article></div></section>}
function Builder(){const [h2,setH2]=useState(1),[o2,setO2]=useState(1),[h2o,setH2o]=useState(1);const ok=2*h2===2*h2o&&2*o2===h2o;const C=({v,set}:{v:number;set:(n:number)=>void})=><span className="counter"><button onClick={()=>set(Math.max(1,v-1))}>−</button><strong>{v}</strong><button onClick={()=>set(v+1)}>+</button></span>;return <section className="page"><h1>Construtor de Reações</h1><p>Ajuste os coeficientes até ter a mesma quantidade de átomos nos dois lados.</p><div className="equation builder"><C v={h2} set={setH2}/> H₂ + <C v={o2} set={setO2}/> O₂ → <C v={h2o} set={setH2o}/> H₂O</div><div className="result"><p>H: esquerda {2*h2} | direita {2*h2o}</p><p>O: esquerda {2*o2} | direita {h2o}</p></div>{ok&&<div className="success" onLoad={()=>track('equation_balanced')}>✅ Equação equilibrada!</div>}</section>}
function Glossary(){const [q,setQ]=useState(''),[terms,setTerms]=useState<Term[]>(fallbackTerms);useEffect(()=>{if(!supabase)return;supabase.from('glossary_terms').select('term_pt,definition_pt,example,libras_status').order('term_pt').then(({data})=>{if(data?.length)setTerms(data.map(x=>({term:x.term_pt,definition:x.definition_pt,example:x.example,librasStatus:x.libras_status})))})},[]);const list=useMemo(()=>terms.filter(t=>t.term.toLowerCase().includes(q.toLowerCase())),[q,terms]);return <section className="page"><h1>Glossário Bilíngue</h1><p>Os sinais-termo serão incluídos somente após validação.</p><input className="search" aria-label="Pesquisar no glossário" placeholder="Pesquisar termo" value={q} onChange={e=>setQ(e.target.value)}/>{list.map(t=><article className="panel" key={t.term}><h2>{t.term}</h2><p>{t.definition}</p>{t.example&&<p><strong>Exemplo:</strong> {t.example}</p>}<Libras label={t.librasStatus==='validated'?'Vídeo em Libras validado':'Vídeo validado será inserido aqui'}/></article>)}</section>}
function Missions(){const items=['Por que o ferro enferruja?','Por que o bolo cresce?','Como funciona um comprimido efervescente?','De onde vem o CO₂?','Por que alimentos mudam durante o cozimento?'];return <section className="page"><h1>Missões do Cotidiano</h1><div className="stack">{items.map((x,i)=><details className="panel" key={x}><summary>{i+1}. {x}</summary><p>Observe o fenômeno, identifique a transformação e responda: <strong>para que esse conhecimento serve na vida?</strong></p></details>)}</div></section>}
function Achievements(){return <section className="page"><h1>Minhas Conquistas</h1><p>Sem ranking: o foco é acompanhar o seu próprio percurso.</p><div className="grid">{['Primeiro Cientista','Detetive Químico','Experimento Concluído','Equação Equilibrada','Explorador do Cotidiano'].map(x=><article className="card static" key={x}><span className="icon">🏅</span><h3>{x}</h3></article>)}</div></section>}
function About(){return <section className="page"><h1>Sobre o ReAção Visual</h1><p>Produto educacional bilíngue criado desde o início para estudantes surdos, articulando Libras, Língua Portuguesa escrita, Pedagogia Visual e DUA.</p><div className="grid"><article className="panel"><h2>🤟 Bilinguismo</h2><p>Libras aparece junto aos conceitos e não como tradução posterior.</p></article><article className="panel"><h2>👁️ Pedagogia Visual</h2><p>Imagens, modelos, cores funcionais e experimentos ajudam a construir significado.</p></article><article className="panel"><h2>🌈 DUA</h2><p>Diferentes formas de engajamento, representação e expressão.</p></article><article className="panel"><h2>🌍 Vida real</h2><p>Química conectada à saúde, tecnologia, sustentabilidade, cidadania e inclusão.</p></article></div></section>}
const router=createBrowserRouter([{path:'/',element:<Shell/>,children:[{index:true,element:<Home/>},{path:'explorar',element:<Explore/>},{path:'detetive',element:<Detective/>},{path:'laboratorio',element:<Lab/>},{path:'construtor',element:<Builder/>},{path:'glossario',element:<Glossary/>},{path:'missoes',element:<Missions/>},{path:'conquistas',element:<Achievements/>},{path:'sobre',element:<About/>}]}]);
export default function App(){return <RouterProvider router={router}/>}
